version: '3.9'
services:
  inventory.api:
    build: .
    image: inventory.api:dev
    container_name: inventory-api
    restart: unless-stopped
    environment:
      POSTGRES_DSN: "postgres://${DB_USER:-catalog_admin}:${DB_PASSWORD}@pg:5432/${DB_NAME:-catalog}?sslmode=disable"
    ports:
      - "8200:8000"
