openapi: 3.1.0
info:
  title: Notification API
  version: v1
paths:
  /email:
    post:
      summary: Send an email notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailRequest'
      responses:
        '200':
          description: Queued
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /healthz:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
components:
  schemas:
    EmailRequest:
      type: object
      properties:
        to:
          type: string
          format: email
        subject:
          type: string
        body:
          type: string
      required:
        - to
        - subject
        - body
