version: "3.9"
services:
  pg:
    image: postgres:16-alpine
    container_name: payment-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-catalog_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-catalog}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  payment.api:
    build:
      context: .
      dockerfile: Dockerfile
    image: payment.api:dev
    container_name: payment-api
    depends_on:
      - pg
    restart: unless-stopped
    environment:
      # Use a lib/pq compatible DSN when running under Go
      ConnectionStrings__PaymentDb: "postgres://${DB_USER:-catalog_admin}:${DB_PASSWORD}@pg:5432/${DB_NAME:-catalog}?sslmode=disable"
    ports:
      - "7001:7001"
      - "7002:8080"

volumes:
  pgdata:
