version: "3.9"
services:
  pg:
    image: postgres:16-alpine
    container_name: analytics-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-catalog_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-catalog}
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  analytics.api:
    build:
      context: .
      dockerfile: Dockerfile
    image: analytics.api:dev
    container_name: analytics-api
    depends_on:
      - pg
    restart: unless-stopped
    environment:
      ConnectionStrings__AnalyticsDb: "postgresql+asyncpg://${DB_USER:-catalog_admin}:${DB_PASSWORD}@pg:5432/${DB_NAME:-catalog}"
    ports:
      - "8000:8000"

volumes:
  pgdata:





