version: "3.9"
services:
  review.api:
    build:
      context: .
      dockerfile: Dockerfile
    image: review.api:dev
    container_name: review-api
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8500:8000"





