name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

        run: |
          for proj in services/*/*.Tests/*.csproj; do
            echo "Testing $proj"
            dotnet test "$proj" --no-build --collect:"XPlat Code Coverage"
          done

      - name: Sync Kong config
        uses: kong/deck@v1
        with:
          command: sync
          config: services/Gateway/kong.yml
      - name: Push images
        if: github.ref == 'refs/heads/main'
        run: docker compose -f services/docker-compose.yml push

