name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install tools
        run: |
          pip install flake8 poetry
          npm install -g eslint
      - name: Run tests and linters
        run: |
          for proj in services/*/*.Tests/*.csproj; do
            echo "Testing $proj"
            dotnet test "$proj" --no-build --collect:"XPlat Code Coverage"
          done
          (cd services/Payment && golangci-lint run && go test ./... -coverprofile=coverage.out)
          (cd services/Admin && poetry install --no-interaction && flake8 app tests && poetry run pytest --cov)
          (cd services/Analytics && poetry install --no-interaction && flake8 app tests && poetry run pytest --cov)
          (cd frontend && npm ci --force && npx eslint src && npm test --ci --silent --coverage)
      - name: Build images
        run: docker compose -f services/docker-compose.yml build
      - name: Sync Kong config
        uses: kong/deck@v1
        with:
          command: sync
          config: services/Gateway/kong.yml
      - name: Push images
        if: github.ref == 'refs/heads/main'
        run: docker compose -f services/docker-compose.yml push

