name: CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Run tests
        run: |
          for proj in services/*/*.Tests/*.csproj; do dotnet test "$proj" --no-build; done
          (cd services/Payment && go test ./...)
          (cd frontend && npm ci && npm test --ci --silent)
      - name: Build images
        run: docker compose -f services/docker-compose.yml build
      - name: Sync Kong config
        uses: kong/deck@v1
        with:
          command: sync
          config: services/Gateway/kong.yml
