name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push images
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          for d in services/*/Dockerfile; do
            name=$(basename $(dirname $d) | tr '[:upper:]' '[:lower:]')
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --tag ghcr.io/${{ github.repository_owner }}/$name:$VERSION \
              --push \
              -f $d $(dirname $d)
          done
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
